# Generated by Django 4.2.5 on 2023-11-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_remove_wishlist_item_wishlist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
