# Generated by Django 4.2.5 on 2023-11-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='views_count',
        ),
    ]
