# Generated by Django 4.2.5 on 2023-11-17 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ('-created_at',)},
        ),
    ]
