# Generated by Django 4.2.5 on 2023-11-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversationmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={},
        ),
    ]
